apiVersion: v1
kind: Service
metadata:
  name: edureka
spec:
  selector:
    app: edureka
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Exposes the service outside the cluster
